language: python
sudo: false
# pypy2.7 is broken (https://github.com/travis-ci/travis-ci/issues/8103#issuecomment-387327744)
python:
  - "2.7"
  - "3.6"
  - "pypy3.5"
install: pip install tox-travis python-coveralls
script: tox -- -v
after_success: cd tests && coveralls
